//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AutoPFA.rc
//
#define IDD_BTN_IMPORT                  3
#define ID_BTN_IMPORT                   3
#define ID_BTN_SAVE                     4
#define IDD_ABOUTBOX                    100
#define IDD_MODELDATAVIEW               101
#define IDD_PAGEFITLOSS                 102
#define IDD_DLGMODELDATA                103
#define IDR_GRAPHVIEW_TMPL              105
#define IDD_DLGOUTPUTCONTROL            106
#define IDD_PAGENOTSHOWOUTATT           108
#define IDD_PAGE_JUNOUTCONTROL          109
#define IDR_MAINFRAME                   128
#define IDR_AUTOPFTYPE                  129
#define IDD_DLGSCENARIOMANAGE           130
#define IDD_SUMMARY                     131
#define IDD_DETAILS                     132
#define IDB_PIPE                        135
#define IDB_BRANCH                      136
#define IDB_RESVIOR                     137
#define IDB_ASSIGNFLOW                  138
#define IDB_ASSIGNPRESS                 139
#define IDB_AREACHANGE                  140
#define IDB_RELIEF                      141
#define IDB_TEEWYE                      142
#define IDB_VALVE                       143
#define IDB_CONTROL                     144
#define IDB_CHECK                       145
#define IDB_DEADEND                     146
#define IDB_GASACUM                     147
#define IDB_SURGE                       148
#define IDB_LIQUIDACUM                  149
#define IDB_BREAKER                     150
#define IDB_SPRAY                       151
#define IDB_PUMP                        152
#define IDB_BITMAP19                    153
#define IDB_GENERAL                     154
#define IDC_BRANCH                      156
#define IDC_CURSOR2                     162
#define IDC_BEND                        162
#define IDC_RESERVIOR                   163
#define IDC_ASSIGNFLOW                  164
#define IDC_ASSIGNPRESS                 165
#define IDC_AREACHANGE                  166
#define IDC_RELIEF                      167
#define IDC_TEEWYE                      168
#define IDC_VALVE                       169
#define IDC_CONTROL                     170
#define IDC_CHECK                       171
#define IDC_DEADEND                     172
#define IDC_GASACCUM                    173
#define IDC_SURGE                       174
#define IDC_LIQUIDACCUM                 175
#define IDC_BREAKER                     176
#define IDC_SPRAY                       177
#define IDC_PUMP                        178
#define IDC_CURSOR19                    179
#define IDC_VOLUME                      179
#define IDC_GENERAL                     180
#define IDB_PALETTE                     181
#define IDD_SYSPROPER                   182
#define IDD_FUILDDATA                   183
#define IDD_VISCOSMODEL                 184
#define IDD_CONDITION                   185
#define IDD_SCENARIONAME                186
#define IDD_DLGWORKSPACEREF             187
#define IDD_GRAPHICSREF                 188
#define IDD_COLORFONTREF                189
#define IDB_RESVIOR75                   190
#define IDB_RESVIOR50                   191
#define IDB_RESVIOR25                   192
#define IDR_WORKSPACEBAR                194
#define IDD_COMMON                      196
#define IDD_PIPE                        196
#define IDD_DLGFIND                     197
#define IDD_PAGEPIPEMODEL               198
#define IDD_DLGJUN                      199
#define IDD_PAGEBRANCH1                 200
#define IDD_PAGERESERVIOR1              201
#define IDD_PAGEFLOW1                   202
#define IDD_PAGEPRESS1                  203
#define IDD_DLGTWOEND                   204
#define IDD_DLGONEElE                   205
#define IDD_DLGONEEND                   206
#define IDD_PAGEPIPEDIR                 207
#define IDD_PAGEDEPTHLOSS               208
#define IDD_DLGBASISAREA                209
#define IDD_AREACHANGEMODEL             210
#define IDD_DLGPARAMUNIT                211
#define IDD_PAGEUNIT                    212
#define IDD_RELIEFMODEL                 213
#define IDD_TEEWYEMODEL                 214
#define IDD_VALVEMODEL                  215
#define IDD_CHECKMODEL                  216
#define IDD_LIQUIDACCUMMODEL            217
#define IDD_BREAKERMODEL                218
#define IDD_SPRAYMODEL                  219
#define IDD_GENERALMODEL                220
#define IDD_CONTROLMODEL                221
#define IDD_SHORTPIPEMODEL              222
#define IDD_RESTRICTORMODEL             223
#define IDD_GASACCUMMODEL               224
#define IDD_SURGEMODEL                  225
#define IDD_PUMPMODEL                   226
#define IDD_VARIABLESPEED               227
#define IDD_DESIGNFACTOR                228
#define IDD_DLGINITPRESSGUESS           229
#define IDD_DIAOPTION                   230
#define IDD_DLGAREACHANGEOPTION         231
#define IDD_ASSIGNFLOWOPTION            232
#define IDD_ASSIGNPRESSOPTION           233
#define IDD_BRACHOPTION                 234
#define IDD_CHECKOPTION                 235
#define IDD_CONTROLOPTION               236
#define IDD_DEADENDOPTION               237
#define IDD_GASACCUMOPTION              238
#define IDD_GENERALOPTION               239
#define IDD_LIQUIDACCUMOPTION           240
#define IDD_PUMPOPTION                  241
#define IDD_RELIEFOPTION                242
#define IDD_RESERVIOROPTION             243
#define IDD_SPRAYOPTION                 244
#define IDD_SURGEOPTION                 245
#define IDD_TEEWYEOPTION                246
#define IDD_BREAKEROPTION               247
#define IDD_VALVEOPTION                 248
#define IDD_TWOSPECIAL                  249
#define IDD_THREESPECIAL                250
#define IDD_PERIODIC                    251
#define IDD_INERTIALDATA                252
#define IDD_INITTRANS                   253
#define IDD_TRANSTABLE                  254
#define IDD_TARASDATASHEEP              255
#define IDD_PAGETRANS2                  256
#define IDD_PAGETRANS3                  257
#define IDD_PAGETRANS1                  258
#define IDD_PAGETRANS0                  259
#define IDD_FOURQUADTABLE               260
#define IDD_PUMPDATASHEEP               261
#define IDD_TRANTRIGER                  262
#define IDD_PAGETRANS5                  264
#define IDD_PAGEPUMPTRANS               265
#define IDB_ANGEL2                      267
#define IDB_ANGEL1                      268
#define IDD_DLGTABVIEW                  272
#define IDD_DATATABLE                   275
#define IDD_DATALIST                    276
#define IDD_PAGEPIPEOPTION              279
#define IDD_DLGSTEADYSET                280
#define IDD_PAGETOLERANCE               281
#define IDD_PAGEOTHER                   283
#define IDD_DlGTOLERANCE                284
#define IDD_DLGSECETION                 285
#define IDD_DLGTRANSIENTSET             286
#define IDD_DLGPUMPCONFIG               289
#define IDD_PAGEPUMPDATA                290
#define IDB_BITCURVE                    291
#define IDB_BITCURVEH                   291
#define IDD_PAGECHART                   292
#define IDD_RAWDATATABLE                294
#define IDB_BITCURVEP                   295
#define IDD_DLGCHART                    298
#define IDD_GENRALCURVE                 300
#define IDD_PAGECONFIG                  303
#define IDB_BITMAPK                     304
#define IDD_PAGESTATUS                  306
#define IDD_DLGCHECKLIST                307
#define IDB_BITABRUPTE                  308
#define IDB_BITCONICALE                 309
#define IDB_BITABRUPTC                  310
#define IDB_BITCONICALC                 311
#define IDB_BITSHARP                    312
#define IDB_BITROUND                    313
#define IDB_BITCHANGE                   314
#define IDB_BITWAY                      315
#define IDB_MDICLIENT                   317
#define IDD_DLGCHANGEUNIT               318
#define IDB_UESOFTCI                    319
#define IDR_GRAPH                       324
#define IDD_VIEWCHART                   326
#define IDD_DLGSELGRAPHDATA             327
#define IDD_PAGEGRAPH                   328
#define IDB_BEND                        329
#define IDD_PAGEBENDMODEL               330
#define IDB_BITMAPBEND                  331
#define IDB_BITMAPELBOW                 332
#define IDB_BITMAPMITRE                 333
#define IDR_GRAPHBAR                    335
#define IDB_BITMAPPRE                   342
#define IDB_BITMAPNEXT                  344
#define IDD_DLGOPTPARAMETER             345
#define IDD_DLGOPTCONST                 346
#define IDB_OPT1                        352
#define IDB_OPTWATERHAMMER              353
#define IDD_DLGOPTCONTROL               355
#define IDD_PAGEOPTCONTRALTWO           358
#define IDD_DLGOPTRESULT                362
#define IDD_DLGOPTCHECKIN               363
#define IDD_PAGEOPTCHECKIN_PIPENET      364
#define IDD_DLGOPTPROGRESS              365
#define IDD_PREVIEW                     366
#define IDD_DLG_UndefinedObjects        368
#define IDD_Dlg_CopyData                369
#define IDD_DIALOG1                     370
#define IDD_DLG_OUTPUTCONTROL           370
#define IDD_PAGE_PIPEOUTCONTROL         371
#define IDD_DIALOG2                     372
#define IDD_TRAN_STEP                   372
#define IDC_BCREATCHILD                 1000
#define IDC_TREESCENRIO                 1001
#define IDC_CURSCENARIO                 1002
#define IDC_TABINFO                     1003
#define IDC_TREE1                       1005
#define IDC_TREECOMPONENT               1005
#define IDC_LIST1                       1006
#define IDC_RADIO1                      1007
#define IDC_RADIOALL                    1007
#define IDC_RADIO100                    1007
#define IDC_RPIPE                       1007
#define IDC_RADIOCONICAL                1007
#define IDC_RADIOINTER                  1007
#define IDC_RADIOSIMPLE                 1007
#define IDC_RADIOHANDBOOK               1007
#define IDC_RADIONO                     1007
#define IDC_RADIONONE                   1007
#define IDC_RADIOREL                    1007
#define IDC_RADIOANGEL2                 1007
#define IDC_RADIOABSTOL                 1007
#define IDC_RADIOPFA                    1007
#define IDC_LIST_UndefinedJuns          1007
#define IDC_RADIO2                      1008
#define IDC_RADIOSELECT                 1008
#define IDC_RADIO75                     1008
#define IDC_RJUN                        1008
#define IDC_RADIOEXIT                   1008
#define IDC_RADIODETAILE                1008
#define IDC_RADIODISPRESS               1008
#define IDC_RADIOOFF                    1008
#define IDC_RADIOABS                    1008
#define IDC_RADIOANGEL1                 1008
#define IDC_RADIORELTOL                 1008
#define IDC_RADIOVOLFLOW                1008
#define IDC_RADIOUSERBEP                1008
#define IDC_RADIOMITRE                  1008
#define IDC_RADIOUSER                   1008
#define IDC_LIST_UndefinedProps         1008
#define IDC_RADIO3                      1009
#define IDC_RADIOANCEST                 1009
#define IDC_RADIO50                     1009
#define IDC_ALLPIPE                     1009
#define IDC_RADIOABRUPT                 1009
#define IDC_RADIOINLINE                 1009
#define IDC_RADIODISHEAD                1009
#define IDC_RADIODUALCYCLIC             1009
#define IDC_RADIOABSORREL               1009
#define IDC_RADIO90                     1009
#define IDC_TAB1                        1010
#define IDC_RADIO25                     1010
#define IDC_RADIOUNDEFINE               1010
#define IDC_RADIO4                      1010
#define IDC_RADIOVOLUMEFLOW             1010
#define IDC_RADIOCONSTCV                1010
#define IDC_RADIOSUCTIONPRESS           1010
#define IDC_RADIOABSANDREL              1010
#define IDC_RADIONO90                   1010
#define IDC_STATIC1                     1011
#define IDC_RADIOSPEC                   1011
#define IDC_RADIOCONSTK                 1011
#define IDC_RADIOSUCTIONHEAD            1011
#define IDC_RADIO7                      1011
#define IDC_RADIODUALSEGUEN             1011
#define IDC_RADIOPOWER                  1011
#define IDC_STATIC2                     1012
#define IDC_RADIOVARIABLECV             1012
#define IDC_RADIOWYE                    1012
#define IDC_RADIOAIR                    1012
#define IDC_RADIOVOLUMEFLOW1            1012
#define IDC_RADIOVOLUME                 1012
#define IDC_RADIOEFFIC                  1012
#define IDC_STATIC3                     1013
#define IDC_RADIOABSHEAD                1013
#define IDC_RADIODISHEAD2               1013
#define IDC_STATIC4                     1014
#define IDC_RADIOABSPRESS               1014
#define IDC_RADIOHEAD                   1014
#define IDC_RADIOALWAYS                 1014
#define IDC_STATIC5                     1015
#define IDC_RADIODIFFHEAD               1015
#define IDC_RADIOSYSTEM                 1015
#define IDC_RADIOOPENHEAD               1015
#define IDC_RADIOEXCEED                 1015
#define IDC_STATIC6                     1016
#define IDC_RADIODIFFPRESS              1016
#define IDC_RADIOBELOW                  1016
#define IDC_STATIC7                     1017
#define IDC_STATIC8                     1018
#define IDC_ENAME                       1020
#define IDC_ETEMP                       1021
#define IDC_EDEN                        1022
#define IDC_EVISCOS                     1023
#define IDC_EBULK                       1024
#define IDC_EVAPOR                      1025
#define IDC_COMBO1                      1027
#define IDC_CMBUNIT                     1027
#define IDC_CMBREFTYPE                  1027
#define IDC_CMBCRACKPRESSUNIT           1027
#define IDC_CMBNUMBEL                   1027
#define IDC_CMBEVENTTYPE                1027
#define IDC_CMBTORQUE                   1027
#define IDC_CMBINERIALUNIT              1027
#define IDC_CMBTRANSMODEL               1027
#define IDC_CMBSHOWTYPE                 1027
#define IDC_CMBMATRIX                   1027
#define IDC_CMBMAXSECTION               1027
#define IDC_CMBFLOW                     1027
#define IDC_CMBA                        1027
#define IDC_CMBXUNIT                    1027
#define IDC_COMBO2                      1028
#define IDC_CMBTEMP                     1028
#define IDC_CMBDIAORAREAUNIT            1028
#define IDC_CMBEXITPRESSUNIT            1028
#define IDC_CMBOUTFLOWUNIT              1028
#define IDC_CMBRESSUNIT                 1028
#define IDC_CMBCONDITION                1028
#define IDC_CMBSOURCE                   1028
#define IDC_CMBMINSECTION               1028
#define IDC_CMBORDER                    1028
#define IDC_CMBB                        1028
#define IDC_CMBYUNIT                    1028
#define IDC_COMBO3                      1029
#define IDC_BSETCOLOR                   1029
#define IDC_CMBDEN                      1029
#define IDC_CMBTYPE                     1029
#define IDC_CMBMEDIATEOUTUNIT           1029
#define IDC_CMBVALUE                    1029
#define IDC_CMBMODEL                    1029
#define IDC_CMBPOWER                    1029
#define IDC_CMBC                        1029
#define IDC_COMBO4                      1030
#define IDC_EFONT                       1030
#define IDC_CMBVISCOS                   1030
#define IDC_CMBINDIAUNIT                1030
#define IDC_CMBDENUNIT                  1030
#define IDC_CMBMEDIATEUNIT              1030
#define IDC_CMBHOLEAREAUNIT             1030
#define IDC_CMBCOMPONENT1               1030
#define IDC_CMBMINFLOWUNIT              1030
#define IDC_COMBO5                      1031
#define IDC_BSETFONT                    1031
#define IDC_CMBBULK                     1031
#define IDC_CMBLENUNIT                  1031
#define IDC_CMBFIREKUNIT1               1031
#define IDC_CMBCOMPONENT2               1031
#define IDC_COMBO6                      1032
#define IDC_GRIDCOLOR                   1032
#define IDC_CMBVAPOR                    1032
#define IDC_CMBELASTICITY               1032
#define IDC_CMBLIQUIDTEMPUNIT           1032
#define IDC_CMBFIREKUNIT2               1032
#define IDC_CMBLOCATION1                1032
#define IDC_LISTATRRIBUTE               1033
#define IDC_CMBWAVEUNIT                 1033
#define IDC_CMBGASPRESSUNIT             1033
#define IDC_COMBO9                      1033
#define IDC_CMBLOCATION2                1033
#define IDC_COMBO7                      1034
#define IDC_CMBTHICK                    1034
#define IDC_CMBGASTEMPERATUREUNIT       1034
#define IDC_CMBLOSSTYPE                 1035
#define IDC_CMBGASMASSUNIT              1035
#define IDC_CMBFRICTIONUNIT             1036
#define IDC_CBOTHICH                    1045
#define IDC_EID                         1049
#define IDC_CNAMELIST                   1051
#define IDC_SINJUN                      1052
#define IDC_SOUTJUN                     1053
#define IDC_LISTPIPE                    1055
#define IDC_LISTJUN                     1056
#define IDC_CMBJUNTYPE                  1057
#define IDC_EOUTELE                     1059
#define IDC_EINELE                      1060
#define IDC_CHECKSAME                   1061
#define IDC_CMBNAMELIST                 1062
#define IDC_SINPIPE                     1063
#define IDC_SOUTPIPE                    1064
#define IDC_LISTCOEF                    1065
#define IDC_EDIT1                       1066
#define IDC_EANGEL                      1066
#define IDC_ECVORK                      1066
#define IDC_ESPEEDRATIO                 1066
#define IDC_ELOSSFACTOR                 1066
#define IDC_EDITVALUE                   1066
#define IDC_EDITSPEED                   1066
#define IDC_EFITLOSS                    1066
#define IDC_EFLOWRELAX                  1066
#define IDC_ESTARTTIME                  1066
#define IDC_EBEP                        1066
#define IDC_EDITPARTFULL                1066
#define IDC_EDIT2                       1067
#define IDC_EK                          1067
#define IDC_ECRACKPRESS                 1067
#define IDC_ESETVALUE                   1067
#define IDC_EINITGUESS                  1067
#define IDC_EDITAMPLITUDE               1067
#define IDC_EDITINERIAL                 1067
#define IDC_EPRESSRELAX                 1067
#define IDC_EMAXERROR                   1067
#define IDC_EDIT3                       1068
#define IDC_EELASTICITY                 1068
#define IDC_EEXITPRESS                  1068
#define IDC_EMEDIATEOUT                 1068
#define IDC_EDITNUM                     1068
#define IDC_EMAXITER                    1068
#define IDC_EPCTINCREMENT               1068
#define IDC_EENDFLOW                    1068
#define IDC_EDIT4                       1069
#define IDC_EPOISSONRATIO               1069
#define IDC_EVELOCITY                   1069
#define IDC_EMEDIATEVALUE               1069
#define IDC_EITERSPAN                   1069
#define IDC_ENUM                        1069
#define IDC_EDIT5                       1070
#define IDC_EIDREDUCE                   1070
#define IDC_EMAXVOLUME                  1070
#define IDC_EIDEALSECTION               1070
#define IDC_EWAVE                       1071
#define IDC_ELIQUIDTEMP                 1071
#define IDC_EHOLEAREA                   1071
#define IDC_EDIT7                       1071
#define IDC_ETIMESTEP                   1071
#define IDC_EINDIA                      1072
#define IDC_EWEIGHT                     1072
#define IDC_EDIT8                       1072
#define IDC_ELEN                        1073
#define IDC_ECPCV                       1073
#define IDC_EDIT6                       1074
#define IDC_STATICSHEET                 1074
#define IDC_ETHICK                      1074
#define IDC_EGASPRESS                   1074
#define IDC_EFRICTION                   1075
#define IDC_LISTPIPEDIR                 1075
#define IDC_EGASTEMPERATURE             1075
#define IDC_PIPELIST                    1076
#define IDC_EGASMASS                    1076
#define IDC_LISTSECTION                 1076
#define IDC_RADIO5                      1077
#define IDC_RADIODEPTH                  1077
#define IDC_RADIODEFFPRESS              1077
#define IDC_RADIO6                      1078
#define IDC_RADIOELE                    1078
#define IDC_RADIOTWO                    1079
#define IDC_RADIOONE                    1080
#define IDC_BOX                         1081
#define IDC_COMBO8                      1082
#define IDC_CMBSUPPORT                  1082
#define IDC_EJUNELE                     1083
#define IDC_CMBElEUNIT                  1084
#define IDC_ESURFACEELE                 1085
#define IDC_ESURFACEPRESS               1086
#define IDC_CMBPRESSUNIT                1087
#define IDC_EFUILDTEMP                  1088
#define IDC_CMBTEMPUNIT                 1089
#define IDC_EFUILDDEN                   1090
#define IDC_ECONDTAREA                  1090
#define IDC_UNITTYPELIST                1091
#define IDC_CMBARAEUNIT                 1091
#define IDC_BUTCURUNIT                  1094
#define IDC_EGRAVITY                    1095
#define IDC_EATMOSPHERICPRESS           1096
#define IDC_EATMOSPHERICTEMP            1097
#define IDC_ERETRANSLAM                 1098
#define IDC_ERETRANSTURB                1099
#define IDC_CMBPRESS                    1100
#define IDC_CMBMATIRAIL                 1101
#define IDC_CMBSIZE                     1102
#define IDC_RADIOASSIGN                 1103
#define IDC_RADIOCALC                   1104
#define IDC_EC1                         1105
#define IDC_RADIOSHARP                  1106
#define IDC_RADIOROUND                  1107
#define IDC_RADIOREENTRART              1108
#define IDC_RADIOCUSTOM                 1109
#define IDC_CMBDEPTNELEUNIT             1110
#define IDC_RADIOIN                     1111
#define IDC_RADIOOUT                    1112
#define IDC_RADIOMASSFLOW               1113
#define IDC_EFLOWRATE                   1114
#define IDC_CMBFLOWUNIT                 1115
#define IDC_RADIOSTATIC                 1116
#define IDC_RADIOSTAG                   1117
#define IDC_EPRESS                      1118
#define IDC_EDIAORAREA                  1119
#define IDC_STATICCVORK                 1120
#define IDC_EPIPEFACTOR                 1120
#define IDC_TABCV                       1121
#define IDC_EFITFACTOR                  1121
#define IDC_RADIOPRESS                  1122
#define IDC_EPARANUM                    1122
#define IDC_RADIOOPENPRESS              1123
#define IDC_CHECKEXIT                   1124
#define IDC_CMBVELOCITYUNIT             1125
#define IDC_EELASTIC                    1126
#define IDC_CMBELASTICUNIT              1127
#define IDC_EINITVOLUME                 1128
#define IDC_CMBVOLUMEUNIT               1129
#define IDC_RADIOOTHER                  1131
#define IDC_RADIORCURVE                 1133
#define IDC_RADIOVARIABLEK              1134
#define IDC_TABKR                       1135
#define IDC_CHECKANTIREVERSE            1136
#define IDC_CHECKCHECKVALVE             1137
#define IDC_RADIOTABLECV                1138
#define IDC_BOX1                        1139
#define IDC_BOX2                        1140
#define IDC_LISTAREA                    1141
#define IDC_STATICNOTE                  1143
#define IDC_STATICEXIT                  1144
#define IDC_RADIOCHANGE                 1145
#define IDC_CMBHANDBOOK                 1146
#define IDC_CMBEXITPRESS                1147
#define IDC_RADIOPRV                    1148
#define IDC_RADIOPSV                    1149
#define IDC_RADIOFCV                    1150
#define IDC_RADIOPDCV                   1151
#define IDC_CHECKALWAYS                 1152
#define IDC_CHECKDEFAULT                1153
#define IDC_RADIOFULLOPEN1              1154
#define IDC_RADIOCLOSS1                 1155
#define IDC_RADIOFULLOPEN2              1156
#define IDC_RADIOCLOSE2                 1157
#define IDC_RADIOTYPE1                  1158
#define IDC_RADIOTYPE2                  1159
#define IDC_RADIOSTAGN                  1160
#define IDC_RADIOCV                     1161
#define IDC_RADIOK                      1162
#define IDC_EDITKORCV                   1163
#define IDC_EDITSETVALVE                1164
#define IDC_CMBSETUNIT                  1165
#define IDC_EDEFFICPRESS                1166
#define IDC_CMBDEFFICPRESSUNIT          1167
#define IDC_CHECKPIPE                   1168
#define IDC_CMBINDIA                    1169
#define IDC_EAREA                       1170
#define IDC_CMBAREA                     1171
#define IDC_CMBLEN                      1172
#define IDC_EELECHANFE                  1173
#define IDC_CMBELECHANGE                1174
#define IDC_CHECKMODEL                  1175
#define IDC_EINFLOWCD                   1176
#define IDC_EOUTFLOWCD                  1177
#define IDC_EFLOWAREA                   1178
#define IDC_CMBAREAUNIT                 1179
#define IDC_EPOLYCONST                  1180
#define IDC_RADIOACTUAL                 1181
#define IDC_RADIOSPECITY                1182
#define IDC_STATICGAS                   1183
#define IDC_EINITPRESS                  1184
#define IDC_EMINVOLUME                  1185
#define IDC_STATICPRESS                 1186
#define IDC_RADIOCONST                  1187
#define IDC_RADIOVARIABLE               1188
#define IDC_CHECKCV                     1189
#define IDC_ECV                         1190
#define IDC_RADIOCLOSE                  1191
#define IDC_RADIOOPEN                   1192
#define IDC_CMBOPENPRESSUNIT            1193
#define IDC_EOPENPRESS                  1194
#define IDC_CMBSURFACEPRESSUNIT         1195
#define IDC_RADIODUAL                   1196
#define IDC_RADIOBREAKER                1197
#define IDC_RADIORELEASE                1198
#define IDC_RADIO3STAGE                 1199
#define IDC_EINFLOW                     1200
#define IDC_CMBINFLOWUNIT               1201
#define IDC_EOUTFLOW                    1202
#define IDC_EINJUNID                    1203
#define IDC_EOUTJUNID                   1204
#define IDC_EINPIPEID                   1205
#define IDC_EOUTPIPEID                  1206
#define IDC_RADIOFIREK                  1207
#define IDC_RADIOSPRAY                  1208
#define IDC_RADIOSPARGER                1209
#define IDC_EHOLENUM                    1210
#define IDC_STATICHOLEAREA              1211
#define IDC_STATICHOLENUM               1212
#define IDC_STATICGEOMETRY              1213
#define IDC_STATICSQUR                  1214
#define IDC_RADIOCURVE                  1215
#define IDC_RADIOVOLUMEFLOE             1216
#define IDC_CMBFLOWRATEUNIT             1218
#define IDC_CMBSUCTIONPRESSUNIT         1219
#define IDC_ESUCTIONPRESS               1220
#define IDC_CHECKSUBMERGE               1221
#define IDC_RADIOMASS                   1222
#define IDC_STATICFLOW                  1223
#define IDC_JUMP                        1224
#define IDC_BOXOPTION                   1226
#define IDC_CHECKINITPRESS              1227
#define IDC_RADIOFIALOPEN               1228
#define IDC_RADIOFULLOPEN               1229
#define IDC_RADIOCLOSS                  1230
#define IDC_RADIOIGNORE                 1231
#define IDC_RADIOOFFFLOW                1232
#define IDC_RADIOIPAR                   1233
#define IDC_RADIOIPARALLEL              1233
#define IDC_RADIOISERIES                1234
#define IDC_RADIOOFFNOFLOW              1235
#define IDC_CHECKINITHEIGHT             1236
#define IDC_EINITHEIGHT                 1237
#define IDC_CMBHEIGHT                   1238
#define IDC_STATICCAPTION               1239
#define IDC_CHECK1                      1240
#define IDC_CHECKREPEAT                 1240
#define IDC_CHECKKEEPTRACK              1240
#define IDC_CHECKVARIABLER              1240
#define IDC_CHECKPARTFULL               1240
#define IDC_CHECK2                      1241
#define IDC_CHECKSORT                   1241
#define IDC_TABLE                       1242
#define IDC_CHECK3                      1242
#define IDC_BOX4                        1243
#define IDC_TABLECOFE                   1243
#define IDC_CHECK4                      1243
#define IDC_BOX3                        1244
#define IDC_CHECK5                      1244
#define IDC_RADIOINFINITE               1246
#define IDC_CHECKPERIODIC               1247
#define IDC_CHECKCHOP                   1248
#define IDC_EDITFREQUENCY               1249
#define IDC_CMBAMPLITUDEUNIT            1250
#define IDC_RADIOTIME                   1251
#define IDC_RADIOSINGLE                 1252
#define IDC_STATICUNIT                  1253
#define IDC_STATICANGEL1                1254
#define IDC_STATICANGEL2                1255
#define IDC_TABGENERAL                  1258
#define IDC_TABJUN                      1259
#define IDC_TABPIPE                     1260
#define IDC_LIST                        1262
#define IDC_CMBFLOWTYPE                 1264
#define IDC_EFLOWVALUE                  1265
#define IDC_EABSTOL                     1266
#define IDC_CMBABSTOLUNIT               1267
#define IDC_ERELTOL                     1268
#define IDC_STATICABS                   1269
#define IDC_LISTRESULT                  1270
#define IDC_CHECKSEARCH                 1271
#define IDC_BSEARCH                     1272
#define IDC_BUPDATATABLE                1273
#define IDC_CHECKARTIFICIAL             1274
#define IDC_CMBTIMEUNIT                 1275
#define IDC_ESTOPTIME                   1276
#define IDC_ETOTALlSTEP                 1277
#define IDC_ESTEPTIME                   1278
#define IDC_CMBFREQUENCY                1279
#define IDC_CHECKCAVITATION             1280
#define IDC_ECRITERIA                   1281
#define IDC_EMINFLOW                    1282
#define IDC_BCONFIG                     1283
#define IDC_TAB                         1284
#define IDC_BFITCURVE                   1285
#define IDC_TABLERAW                    1286
#define IDC_BOXRAWDATA                  1287
#define IDC_BOXPRAME                    1288
#define IDC_STATICBIT                   1292
#define IDC_MSCHART1                    1293
#define IDC_BCHART                      1294
#define IDC_BCAHET                      1295
#define IDC_CURVEDATA                   1296
#define IDC_RADIOCALCBEP                1297
#define IDC_STATICBEPUNIT               1298
#define IDC_STATICFLOWUNIT              1299
#define IDC_CVDATA                      1299
#define IDC_BITMAP                      1300
#define IDC_STATICMAP                   1301
#define IDC_LISTUNIT                    1302
#define IDC_TREE                        1303
#define IDC_STATICYUNIT                 1304
#define IDC_BADD                        1305
#define IDC_BMOVE                       1306
#define IDC_BCLEAR                      1307
#define IDC_RADIOBEND                   1307
#define IDC_RADIOELBOW                  1308
#define IDC_ERD                         1309
#define IDC_BCALC                       1310
#define IDC_STATICRANGE                 1311
#define IDC_BUTTON1                     1313
#define IDC_BUTTON2                     1314
#define IDC_EDIT9                       1315
#define IDC_BUTTON3                     1315
#define IDC_BUT_UndefinedObjects        1315
#define IDC_BUT_Invert                  1315
#define IDC_EDIT10                      1316
#define IDC_RADIO8                      1316
#define IDC_BUTTON4                     1316
#define IDC_BUT_ShowSectionPipe         1316
#define IDC_EDIT11                      1317
#define IDC_BUTTON5                     1317
#define IDC_BUT_ShowTransControl        1317
#define IDC_STATIC9                     1319
#define IDC_STATIC10                    1320
#define IDC_STATIC11                    1321
#define IDC_STATIC12                    1322
#define IDC_STATIC13                    1323
#define IDC_STATIC14                    1325
#define IDC_STATIC15                    1326
#define IDC_RADIO9                      1327
#define IDC_RADIO10                     1328
#define IDC_PROGRESS1                   1332
#define IDC_PROGRESS2                   1333
#define IDC_PREVIEW_AREA                1333
#define IDC_CHECK_PREVIEW               1334
#define IDC_BUT_ShowSteadySet           1335
#define IDC_BUT_ShowSystemProper        1336
#define IDC_STA_UndefinedProps          1337
#define IDC_LIST_UndefinedPipes         1338
#define IDC_AttrList                    1339
#define IDC_BUT_SelectAll               1340
#define IDC_BUT_SelectNone              1341
#define IDC_TAB_NOTSHOWOUT              1342
#define IDC_BTN_ADD                     1343
#define IDC_BTN_DELETE                  1344
#define IDC_LIST_SHOWOUT                1345
#define IDC_COMBO                       1346
#define IDC_COMBO_Unit                  1346
#define IDC_STEP_VALUE                  1347
#define IDC_MAX_STEP                    1348
#define IDC_ADD                         1349
#define IDC_MINUS                       1350
#define ID_MANAGER                      32771
#define ID_SYSTEMPROPER                 32772
#define ID_WORKSPACEREF                 32773
#define ID_ZOOMFIT                      32792
#define ID_ZOOMOUT                      32793
#define ID_ZOOMIN                       32795
#define ID_DELETE                       32796
#define ID_FIND                         32798
#define ID_REVERSE                      32799
#define ID_SHOWDATA                     32800
#define ID_DUPLICATE                    32801
#define ID_FLOWPATH                     32804
#define ID_PARAMUNIT                    32805
#define ID_TRANSANALYSIS                32806
#define ID_STEADYANALYSIS               32807
#define ID_STEADYCONTROL                32808
#define ID_OUTPUTCONTROL                32809
#define ID_SECTIONPIPE                  32810
#define ID_TRANSCONTROL                 32811
#define ID_RUNMODEL                     32812
#define ID_EXPORTCALCFILE               32814
#define ID_CHECKMODEL                   32821
#define ID_SELGRAPHDATA                 32824
#define ID_PFAHELP                      32825
#define ID_VIEW_WORKSPECE               32828
#define ID_VIEW_DATAMODEL               32830
#define ID_VIEW_OUTPUT                  32831
#define ID_BUTTON32832                  32832
#define ID_VIEW_GRAPH                   32833
#define ID_SELECTDATA                   32836
#define ID_COPYDATA                     32837
#define AFX_ID_OPTIMIZATION_RUNOPTIMIZATION 32838
#define AFX_ID_OPTIMIZATION_OPTPARA     32839
#define ID_OPTCONTRAL                   32840
#define ID_OPTANALYSIS                  32841
#define ID_32845                        32845
#define ID_OUTPUTRESULT                 32846
#define ID_PALETTE_BASE                 61446
#define ID_PALETTEPIPE                  61446
#define ID_PALETTEBRANCH                61447
#define ID_PALETTERESERVOIR             61448
#define ID_PALETTEFLOW                  61449
#define ID_PALETTEPRESS                 61450
#define ID_PALETTEAREA                  61451
#define ID_PALETTERELIEF                61452
#define ID_PALETTETEE                   61453
#define ID_PALETTEVALVE                 61454
#define ID_PALETTECONTROL               61455
#define ID_PALETTECHECK                 61456
#define ID_PALETTEEND                   61457
#define ID_PALETTEGAS                   61458
#define ID_PALETTESURGE                 61459
#define ID_PALETTELIQUID                61460
#define ID_PALETTEBREAKER               61461
#define ID_PALETTESPRAY                 61462
#define ID_PALETTEPUMP                  61463
#define ID_PALETTEVOLUME                61464
#define ID_PALETTEBEND                  61464
#define ID_PALETTEGENERAL               61465
#define ID_PALETTESELCTDRAW             61466
#define ID_PALETTESELCTZOOM             61467
#define ID_PALETTEBAR                   61472
#define IDS_FUILDTEMP                   61476
#define IDS_FUILDVISCOS                 61477
#define IDS_COMPONENTNAME               61478
#define IDS_STRPIPE                     61479
#define IDS_STRBRANCH                   61480
#define IDS_STRRESERVIOR                61481
#define IDS_STRASSIGNFLOW               61482
#define IDS_STRASSIGNPRESS              61483
#define IDS_STRAREACHANGE               61484
#define IDS_STRRELIEF                   61485
#define IDS_STRTEEWYE                   61486
#define IDS_STRVALVE                    61487
#define IDS_STRCONTROL                  61488
#define IDS_STRCHECK                    61489
#define IDS_STRDEADEND                  61490
#define IDS_STRGASACCUM                 61491
#define IDS_STRSURGE                    61492
#define IDS_STRLIQUIDACCUM              61493
#define IDS_STRBREAKER                  61494
#define IDS_STRSPRAY                    61495
#define IDS_STRPUMP                     61496
#define IDS_STRGENERAL                  61497
#define IDS_DELSCENARIOMSG              61498
#define IDS_PROMOTESCENARIOMSG          61499
#define IDS_SCENARIONAMEERROR           61500
#define IDS_NAMEERROR                   61501
#define IDS_STRCLOSEJUN                 61502
#define IDS_JUNTEXTCOROL                61503
#define IDS_PIPETEXTCOLOR               61504
#define IDS_UNDEFINEITEM                61505
#define IDS_SELECTITEM                  61506
#define IDS_PIPECOLOR                   61507
#define IDS_STRBKCOROL                  61508
#define IDS_FUILDNAME                   61509
#define IDS_FUILDDEN                    61510
#define IDS_JUNPOINT                    61511
#define IDS_STARTPT                     61512
#define IDS_ENDPT                       61513
#define IDS_INJUNNUM                    61514
#define IDS_OUTJUNNUM                   61515
#define ID_CREATCHILD                   61516
#define ID_CLONEWITHCHILD               61517
#define ID_CLONEWITHOUT                 61518
#define ID_PROMOTE                      61519
#define ID_DELSCENARIO                  61520
#define ID_RENAME                       61521
#define IDS_SELECTSCENARIO              61522
#define IDS_DELCOMPONENT                61523
#define IDS_BULKMDULUS                  61524
#define IDS_VAPORPRESSURE               61525
#define IDS_STRINELE                    61526
#define IDS_STROUTELE                   61527
#define IDS_STRINDIA                    61528
#define IDS_STRLEN                      61529
#define IDS_STRWAVESPEED                61530
#define IDS_STRMATERIAL                 61532
#define IDS_STRSIZE                     61533
#define IDS_STRPIPETYPE                 61534
#define IDS_STRTHICK                    61535
#define IDS_STRELASTICITY               61536
#define IDS_STRPOSSIONRATIO             61537
#define IDS_STRCALCWAVE                 61538
#define IDS_STRSUPPORT                  61539
#define IDS_STRFRICTIONMODEL            61540
#define IDS_STRFRICTION                 61541
#define IDS_STRPIPEDEPTH                61542
#define IDS_STRSURFACEPRESS             61543
#define IDS_STRIMPOSEFLOE               61544
#define IDS_STRIFLOWDIR                 61545
#define IDS_STRFLOWDIR                  61545
#define IDS_STRFLOWRATE                 61546
#define IDS_STRLOSSFACTOR               61547
#define IDS_STRPRESSURE                 61548
#define IDS_STRTYPE                     61549
#define IDS_STRANGLE                    61550
#define IDS_STREXITPRESS                61551
#define IDS_STRREOPENPRESS              61552
#define IDS_STRELASTIC                  61553
#define IDS_STRINITVOLUME               61554
#define IDS_STRCRACKPRESS               61555
#define IDS_STRORIFICEINCDA             61556
#define IDS_STRORIFICEOUTCDA            61557
#define IDS_STRLIQUIDTEMP               61558
#define IDS_STRCLOSEVALVE               61559
#define IDS_STRCONSTK                   61560
#define IDS_STRCONSTCV                  61561
#define IDS_STRMASSFLOW                 61562
#define IDS_STRVOLUMEFLOW               61563
#define IDS_STRPRESSLOSS                61564
#define IDS_STRHEADLOSS                 61565
#define IDS_STRHEAD                     61566
#define IDS_STRINITGASVOLUME            61567
#define IDS_STRREFGASVOLUME             61568
#define IDS_STRSPEEDNOTE                61569
#define IDS_STRTEEOPENMEG               61570
#define IDS_STRDESIGNFACTOR             61571
#define IDS_STRINITGUESS                61572
#define IDS_STRPAGEOPTION               61573
#define IDS_STRPAGETRANS                61574
#define IDS_STRFRISTEVENT               61575
#define IDS_STRSECONDEVENT              61576
#define IDS_STRFRISTTRANS               61577
#define IDS_STRSECONDTRANS              61578
#define IDS_STROPENTRANS                61579
#define IDS_STRCLOSETRANS               61580
#define IDS_STRPAGECTRLTRANS            61581
#define IDS_STRPAGEFAILTRANS            61582
#define IDS_STRINERIALDATA              61583
#define IDS_STRSTARTTRANS               61584
#define IDS_STRTRIPTRANS                61585
#define IDS_STRSTARTDATA                61586
#define IDS_STRFOURQUAD                 61587
#define IDS_STRSUMMARY                  61588
#define IDS_STRDETAILS                  61589
#define IDS_STRNAMEUNIT                 61590
#define IDS_STRCONECTPIPE               61591
#define IDS_STRSPECIALMARK              61592
#define IDS_STRELEDELTAUNIT             61593
#define IDS_STRLOSSMODEL                61594
#define IDS_STRCONTROLSET               61595
#define IDS_STRPOLYTROPIC               61596
#define IDS_STRGASVOLUME                61598
#define IDS_STRGASPRESS                 61599
#define IDS_STRINITPRESS                61600
#define IDS_STRSURGEHEIGH               61601
#define IDS_STRCONSTAREA                61602
#define IDS_STRONEWAYTANK               61603
#define IDS_STRINITHEIGHT               61604
#define IDS_STBASISAREA                 61605
#define IDS_STRSPEEDRATIO               61606
#define IDS_STRCONTROLAPPLY             61607
#define IDS_STRCONTROLPRESSTYPE         61608
#define IDS_STRSUBMERGEPRESS            61609
#define IDS_STREXITCHECK                61610
#define IDS_STRANTIREVERSE              61611
#define IDS_STRMAXVOLUME                61612
#define IDS_STRMINVOLUME                61613
#define ID_SAVESCENARIO                 61614
#define IDS_STRPIPEMODEL                61615
#define IDS_STRFITLOSS                  61616
#define IDS_STRFLOWGUESS                61617
#define IDS_STRFRICTIONFACTOR           61618
#define IDS_STRFITLOSSFACTOR            61619
#define IDS_STRPARAMUN                  61620
#define IDS_STRINITSPEED                61621
#define IDS_STRROTATEINERIA             61622
#define IDS_STRTOLERANCE                61623
#define IDS_STROTHER                    61624
#define IDS_STRCONFIGDATA               61625
#define IDS_STREFFICENCY                61626
#define IDS_STRPOWER                    61627
#define IDS_STRCURVERCONFIG             61628
#define IDS_STRCURVERNPRS               61629
#define IDS_STRCURVERPOWER              61630
#define IDS_STRGRAVITY                  61631
#define IDS_STRATMOSPHERICPRESS         61632
#define IDS_STRRETRANSLAM               61633
#define IDS_STRRETRANSTURB              61634
#define IDS_STRPRESABSTOL               61635
#define IDS_STRFLOWABSTOL               61636
#define IDS_STRPRESRELTOL               61637
#define IDS_STRFLOWRELTOL               61638
#define IDS_STRFLOWRELAX                61639
#define IDS_STRPRESRELAX                61640
#define IDS_STRMAXITERATIONS            61641
#define IDS_STRSECTIONPIPEERROE1        61642
#define IDS_STRIDEALSECTION             61643
#define IDS_STRINTSECTION               61644
#define IDS_STRMODIFYWAVE               61645
#define IDS_STRBVALUE                   61646
#define IDS_MSGNUMERROR                 61646
#define IDS_MSGMAXERROR                 61647
#define IDS_MSGINCREMENTERROR           61648
#define IDS_STRJUNRAWDATA               61649
#define IDS_STRPUMPDATA                 61650
#define IDS_STRSTATUS                   61651
#define IDS_STRCVTABLE                  61652
#define IDS_STRORIFICE                  61653
#define IDS_STRSHORTPIPE                61654
#define IDS_STRVARABLEAREA              61655
#define IDS_STRALLJUN                   61656
#define IDS_MDICLIENTTEXT               61657
#define IDS_STRTRANMAXMIN               61659
#define IDS_STRJUN                      61660
#define IDS_STRUSERDEF                  61661
#define IDS_STRBEND                     61662
#define IDS_STRTRANOUTPUT               61663
#define IDS_NOSOUCEFILE                 61664
#define IDS_STRTRANVALUETYPE            61665
#define IDS_STRTRAN_SPECIAL             61666
#define IDS_STRTRAN_REPEAT1             61667
#define IDS_STRTRAN_REPEAT2             61668
#define IDS_STRTRAN_TRTYPE              61669
#define IDS_STRTRAN_PERIODIC            61670
#define IDS_STRRDNUM                    61672
#define IDS_STRPARTFULL                 61673
#define IDS_STR_CRACKEXITPRESS          61674
#define IDS_STR_MEDIUMACTIVATION        61675
#define IDS_STR_GASPROPORTY             61676
#define IDS_STR_INTERMEDIATECDA         61677
#define IDS_STR_CONNECTPIPENUM          61678

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        373
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1351
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
